### PR TITLE
Cdr4423 qcpv

### PR DESCRIPTION
**Pull request by venglisch**
This is the filter change that caused the QC report to fail.

### CODE REVIEW

**Comment by venglisch** [comment]
The filter has been promoted to PROD and STAGE.

**Comment by bkline** [comment]
I'm confused. I got a request to review this pull request, but by the time I got here it was closed. Did I get here too late? 😕

**Comment by venglisch** [comment]
Oops!  There was a button that said:  Close and comment.  I thought it meant "Close the comment" but I guess it closed the pull request.  Let me see how to open it again.

**Comment by bkline** [comment]
I just re-opened it.

**Comment by venglisch** [comment]
I guess I can close the new pull request I created.

**Comment by bkline** [comment]
> I guess I can close the new pull request ...

No, see comment above.

**Pull request closed without merging**
