### PR TITLE
Fixing URI in document() call containing hash. OCECDR-4425

### PR DESCRIPTION
**Pull request by venglisch**

### CODE REVIEW

**Comment by bkline** [comment]
Do we know that there will always be a hash sign in the attribute value? The new variable is only created if that's true.

**Comment by venglisch** [comment]
Bummer, you're right!  I thought I'm following the same logic as for the fragId variable but the link variable as used to create the URI.  
I've already deleted my local branch so I'll have to send another pull request with a different branch.

**Comment by bkline** [comment]
That's what reviews are for. 🔍 😄

**Comment by venglisch** [comment]
I was wrong.  I had deleted another branch, this was still available so I added the fix.  I don't think I'll have to create another pull request, do I?

**Comment by bkline** [comment]
Perfekt! No new PR needed.

**Pull request merged**
